/// Generates `docs/testbench_voice.js` — the voice-phrase fixture the trip test
/// bench (`docs/testbench.html`) renders.
///
/// It is a TEST so it runs the REAL parser (`parseVoiceCommand` lives in a file
/// that imports Flutter + speech_to_text, so a plain `dart run` script cannot
/// execute it). Regenerate after any parser change with:
///
///     flutter test test/voice_phrase_fixture_test.dart
///
/// The bench then shows, for every phrase, what the app would actually do —
/// the functional check the unit tests can't give the driver.
library;

import 'dart:convert';
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';

import 'package:navbridge/services/voice_commands.dart';

/// Phrases a driver actually says (plus the ones that were mis-parsed before).
const List<String> phrases = [
  // --- canonical ----------------------------------------------------------
  'chỉ đường tới chợ Bến Thành',
  'navigate to Ben Thanh',
  // --- the forms that used to fail ---------------------------------------
  'đường đến chợ Bến Thành',
  'đường tới sân bay Tân Sơn Nhất',
  'dẫn đường về Đà Lạt',
  'dẫn đường tới Vũng Tàu',
  'tìm đường đến Cần Thơ',
  'đến Vũng Tàu',
  'tới Đà Lạt',
  'đi Đà Nẵng',
  'về nhà',
  'chỉ đường về nhà',
  // --- recognizer drops diacritics ---------------------------------------
  'chi duong toi ben thanh',
  'duong den vung tau',
  'dan duong ve da lat',
  'den da nang',
  'tim duong den can tho',
  // --- bare place names ---------------------------------------------------
  'chợ bến thành',
  'sân bay tân sơn nhất',
  'bến xe miền đông',
  'đường nguyễn trãi',
  'quận 7',
  'cà phê võng',
  // --- must STAY control commands ----------------------------------------
  'bắt đầu',
  'đi thôi',
  'dừng lại',
  'kết thúc',
  'phóng to',
  'thu nhỏ',
  'bật tiếng',
  'tắt tiếng',
  'nghe liên tục',
  'dừng nghe',
  'giúp tôi',
  // --- questions go to the assistant -------------------------------------
  'hỏi AI xăng gần nhất',
  'hỏi trợ lý còn bao nhiêu km',
  'thời tiết thế nào',
  'còn bao nhiêu km',
  'bao giờ thì hết đèo',
  'mấy giờ tới nơi',
  // --- plain searches -----------------------------------------------------
  'tìm quán cà phê',
  'tìm kiếm trạm xăng',
];

String typeName(VoiceCommandType t) => t.name;

/// True when [current] and [next] carry the same phrases — the volatile
/// `generated` stamp is ignored, so a run that only changes the clock does not
/// rewrite the committed fixture.
bool _samePhrases(String current, String next) {
  Map<String, dynamic>? payload(String s) {
    final i = s.indexOf('{');
    final j = s.lastIndexOf('}');
    if (i < 0 || j <= i) return null;
    try {
      return jsonDecode(s.substring(i, j + 1)) as Map<String, dynamic>;
    } catch (_) {
      return null;
    }
  }

  final a = payload(current);
  final b = payload(next);
  if (a == null || b == null) return false;
  a.remove('generated');
  b.remove('generated');
  return jsonEncode(a) == jsonEncode(b);
}

void main() {
  test('dumps the voice phrase fixture for the test bench', () {
    final out = <String, dynamic>{
      'generated': DateTime.now().toIso8601String(),
      'parser': 'lib/services/voice_commands.dart parseVoiceCommand()',
      'phrases': [
        for (final p in phrases)
          {
            'phrase': p,
            'type': typeName(parseVoiceCommand(p).type),
            'query': parseVoiceCommand(p).query,
            'navigate': parseVoiceCommand(p).navigate,
          },
      ],
    };
    final f = File('docs/testbench_voice.js');
    // Write ONLY when the parsed phrases actually changed. The fixture is a
    // COMMITTED file, and rewriting it on every run (the `generated` stamp
    // alone) left the working tree dirty after each `flutter test` — which the
    // pre-commit hook reports as "files were modified by this hook" and aborts
    // an otherwise clean commit.
    final next =
        '// Generated by `flutter test test/voice_phrase_fixture_test.dart`\n'
        'window.VOICE_FIXTURE = ${jsonEncode(out)};\n';
    if (!f.existsSync() || !_samePhrases(f.readAsStringSync(), next)) {
      f.writeAsStringSync(next);
    }
    expect(f.existsSync(), isTrue);

    // Guard the behaviour the driver asked for (\"tell the location should
    // start the navigation\"): every destination-ish phrase must navigate.
    for (final p in phrases.sublist(0, 22)) {
      final c = parseVoiceCommand(p);
      expect(
        c.type,
        VoiceCommandType.searchAndNavigate,
        reason: '"$p" should be a destination',
      );
      expect(c.navigate, isTrue, reason: '"$p" should auto-start navigation');
      expect(c.query, isNotEmpty, reason: '"$p" should carry a query');
    }
    // …and the control words must NOT be swallowed by that fallback.
    expect(parseVoiceCommand('đi thôi').type, VoiceCommandType.start);
    expect(parseVoiceCommand('dừng lại').type, VoiceCommandType.stop);
    expect(parseVoiceCommand('tắt tiếng').type, VoiceCommandType.voiceOff);
    expect(
      parseVoiceCommand('thời tiết thế nào').type,
      isNot(VoiceCommandType.searchAndNavigate),
    );
  });
}
